### ISSUE TITLE
/projects/id nu returneaza toate informatiile

### ISSUE THREAD

**Issue by BoldijarPaul** [infoeducatie/infoeducatie-api#118]
cred ca ar fi ok sa se modifice api-ul la /projects/id cu toate informatiile care trebuie afisate, cum ar fi detalii tehnice, cerinte de sistem, etc.. 
nu cred ca  ar avea rost si la /projects sa fie toate

**Comment by robertdolca** [comment]
Ti-as sugera sa modifici in RABL si sa faci un pull request

**Comment by BoldijarPaul** [comment]
unde gasesc toate numele coloanelor din baza de date?
https://github.com/infoeducatie/infoeducatie-api/blob/master/app/models/project.rb
credeam ca aici, dar nu sunt toate

si dupa trebuie sa modific aici ? 
https://github.com/infoeducatie/infoeducatie-api/blob/master/app/views/v1/projects/index.json.rabl
?

**Comment by robertdolca** [comment]
https://github.com/infoeducatie/infoeducatie-api/blob/master/db/schema.rb

**Comment by BoldijarPaul** [comment]
https://github.com/infoeducatie/infoeducatie-api/pull/147
