### ISSUE TITLE
Register user API endpoint

### ISSUE THREAD

**Issue by palcu** [infoeducatie/infoeducatie-api#44]

**Comment by hurrycane** [comment]
Primul pas de registration:
nume, prenume, cnp, data nasterii, seria si nr de buletin, adresa, email, password si confirmare parola.

Pasul 2 detalii despre scoala:
numele scolii, oras, judet, tara, clasa.

Pasul 3 detalii despre lucrare:
titlul lucrarii, categoria, descriere, cerinte tehnice, tehnologii folosite si optional home page, screenshots.

Pasul 4 sau parte a pasului 3:
adauga alti autori ai lucrarii tale (aceleasi fielduri ca la pasul 1 + este participant in tabara da sau nu).
